### ISSUE TITLE
How do I use delphinus with custom theme?

### ISSUE THREAD

**Issue by GoDzM4TT3O** [delphinus/lightline-delphinus#26]
I have a custom theme from https://github.com/sainnhe/lightline_foobar.vim called `neodark_alter`. If I run

```vim
let g:lightline.colorscheme = "neodark_alter"
call lightline#init()
call lightline#colorscheme()
call lightline#update()
```

everytime I open Vim, the theme neodark applies successfully to the statusbar, keeping the powerline gliphs. However, if I add

```vim
let g:lightline = {
      \ 'colorscheme': 'neodark_alter',
      \ }

```

to my `.vimrc` (before/after the delphinus settings), Vim/NeoVim applies the other theme instead, completely ignoring/bypassing delphinus.

What can I do?

Here's my .vimrc: https://github.com/GoDzM4TT3O/dotfiles/blob/master/.vimrc

**Comment by delphinus** [comment]
Sorry for late.

First of all, lightline.vim's colorscheme is a part of the whole theme and closely related to its components. For example, lightline-delphinus has 4 chunks of components in `active.left` (means components exists at the left of statusbar in the active window).

https://github.com/delphinus/lightline-delphinus/blob/348ea3531ee6ec7cb2a5762a8be2c14a9b30c89d/plugin/lightline_delphinus.vim#L44

And the `solarized_improved` colorscheme also has 4 items in `normal.left`. (means the left of statusbar when Vim is in the normal mode).

https://github.com/delphinus/lightline-delphinus/blob/348ea3531ee6ec7cb2a5762a8be2c14a9b30c89d/autoload/lightline/delphinus/colorscheme/solarized_improved.vim#L137

(This file is a “source”. A computed file is placed on [here][])

[here]: https://github.com/delphinus/lightline-delphinus/blob/master/autoload/lightline/colorscheme/solarized_improved.vim

In contrast, your `neodark_alter` colorscheme has only 2 items in its `normal.left`.

https://github.com/sainnhe/lightline_foobar.vim/blob/3f6735f0669c14129c286a6f30696fd87aa20f56/autoload/lightline/colorscheme/neodark_alter.vim#L110

This is the reason. Probably lightline.vim uses the default color for 3rd and 4th chunks.

You should expand your colorschemes for lightline-delphinus, I think.
